---
- name: "Install kea-dhcp server package for DHCP version {{ dhcp_ip_version }}"
  ansible.builtin.apt:
    name: "kea-dhcp{{ dhcp_ip_version }}-server"
    state: present

- name: Copy keys to Kea configuration directory
  ansible.builtin.include_tasks: key_management.yml
  when: kea_ddns_enabled | bool

- name: "Render kea-dhcp configuration for DHCP version {{ dhcp_ip_version }}"
  ansible.builtin.template:
    src: "dhcp{{ dhcp_ip_version }}.json.j2"
    dest: "{{ kea_base_dir }}/kea-dhcp{{ dhcp_ip_version }}.conf"
    owner: root
    group: _kea
    mode: "0640"
  notify: "Reload kea-dhcp{{ dhcp_ip_version }}-server"

- name: "Manage kea-dhcp server service state for DHCP version {{ dhcp_ip_version }}"
  ansible.builtin.systemd:
    name: "kea-dhcp{{ dhcp_ip_version }}-server"
    state: "{{ 'started' if kea_service_manage | bool else 'stopped' }}"
    enabled: "{{ kea_service_manage | bool }}"
    daemon_reload: true
