---
dependency:
  name: galaxy
  options:
    ignore-errors: true
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: kea-ddns-ubuntu2604
    image: geerlingguy/docker-ubuntu2604-ansible:latest
    cgroupns_mode: host
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
    ANSIBLE_ALLOW_BROKEN_CONDITIONALS: "1"
    ANSIBLE_DEPRECATION_WARNINGS: "0"
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    cleanup: cleanup.yml

scenario:
  name: ddns

verifier:
  name: testinfra
  directory: tests/
  options:
    v: true
    p: "no:cacheprovider"
